name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Étape 2: Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3: Se connecter à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4: Extraire les métadonnées (tags, labels) pour Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/erios-project/vllm-audio
          tags: |
            type=sha,event=branch,ref=main,name=${{ github.sha }}
            type=ref,event=branch,ref=main,latest=true,name=latest

      # Étape 5: Construire et pousser l'image Docker avec des variables d'environnement
      - name: Build and Push Docker image with environment variables
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/erios-project/vllm-audio:${{ github.sha }}
            ghcr.io/erios-project/vllm-audio:latest
          labels: ${{ steps.meta.outputs.labels }}